### ISSUE TITLE
Error: JSON.parse

### ISSUE THREAD

**Issue by MattyHello** [AZn5ReD/saplearninghub-pdf-downloader#11]
Hi, 

when I run 

> npm run start 

I get the following errors:

> saplearninghub-pdf-downloader@1.0.0 start C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master
> set NODE_ENV=production && node ./dist/index.js

 in JSON at position 159ig file: SyntaxError: Unexpected token
    at JSON.parse (<anonymous>)
    at Module.<anonymous> (C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:18:938319)
    at t (C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:1:110)
    at C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:1:902
    at Object.<anonymous> (C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:1:913)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Starting script...
(node:20004) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error during puppeteer initialisation: Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary.
    at f.launch (C:\Users\MatiasHahn\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:1:1222145)
TypeError: Cannot read property 'browser' of undefined
    at C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:18:946766
    at s (C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:1:1066045)
    at Generator._invoke (C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:1:1065798)
    at Generator.forEach.e.<computed> [as next] (C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:1:1066402)
    at t (C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:1:12980)
    at c (C:\Users\Downloads\saplearninghub-pdf-downloader-master\saplearninghub-pdf-downloader-master\dist\index.js:1:13191)

Did I do anything wrong? Can you please help me?

Thank you!

**Comment by AZn5ReD** [comment]
Did you make "npm install" first in the root of the project ?
Seems like puppeteer didn't installed the browser.

**Comment by MattyHello** [comment]
Yes, sure. 

I found this regarding the installation of puppeteer:

https://github.com/puppeteer/puppeteer/issues/6560

I think I may have a similar issue?

**Comment by AZn5ReD** [comment]
Yes ! It seems like npm didn't installed chromium.
But if you configured the "config.json" file well : `"CHROME_EXE": "/usr/bin/google-chrome"`
You would not need to download chromium.

If it still doesn't work and you have chrome installed, you could try the GUI version : https://github.com/AZn5ReD/saplearninghub-pdf-downloader-gui
