### ISSUE TITLE
Can't connect :(

### ISSUE THREAD

**Issue by chunhui323** [AZn5ReD/saplearninghub-pdf-downloader#20]
Dear AZn5ReD,

Thank You for the wonderful downloader, If you know what am I missing? don't worry about the password. it's fake.

user123@laptop999 MINGW64 ~
$ cd saplearninghub-pdf-downloader
(base)
user123@laptop999 MINGW64 ~/saplearninghub-pdf-downloader (master)
$ npm run start --  --chrome="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" --debug="false" --url="https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/HA200_EN_Col12_R1.3/index.html" --login="S0020311123" --password="coolpassword" --target="C:\\Users\\user123\\Downloads\\SapLearningHub"

> saplearninghub-pdf-downloader@1.0.0 start C:\Users\user123\saplearninghub-pdf-downloader
> set NODE_ENV=production && node --no-deprecation ./dist/index.js  "--chrome=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "--debug=false" "--url=https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/HA200_EN_Col12_R1.3/index.html" "--login=S0020311123" "--password=coolpassword" "--target=C:\Users\user123\Downloads\SapLearningHub"

Starting script...
Going to: https://performancemanager.successfactors.eu/sf/learning?company=learninghub
Entering login: S0020311123
Entering password: ***
Submiting...
Redirected to: https://accounts.sap.com/saml2/idp/usso/Learning_Hub
Can't connect :(
Error: Error during init
    at C:\Users\user123\saplearninghub-pdf-downloader\dist\index.js:18:853117
    at s (C:\Users\user123\saplearninghub-pdf-downloader\dist\index.js:1:1024948)
    at Generator._invoke (C:\Users\user123\saplearninghub-pdf-downloader\dist\index.js:1:1024701)
    at Generator.forEach.e.<computed> [as next] (C:\Users\user123\saplearninghub-pdf-downloader\dist\index.js:1:1025305)
    at t (C:\Users\user123\saplearninghub-pdf-downloader\dist\index.js:1:13893)
    at c (C:\Users\user123\saplearninghub-pdf-downloader\dist\index.js:1:14104)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(base)
user123@laptop999 MINGW64 ~/saplearninghub-pdf-downloader (master)

**Comment by reallyallnamestaken** [comment]
Confirmed. Getting exact same issue. Seem to be timing issue. If you access the site manually this will be the point where you observe some waiting for the redirect. 
As a workaround I run in test mode and enter "rs" when it fails. Eventually it will go through. may take quite a few times though.

**Output:**

Redirected to: https://accounts.sap.com/saml2/idp/usso/Learning_Hub
Can't connect :(
Error: Error during init
at _callee3$ (/home/user/git/saplearninghub-pdf-downloader/src/main.js:30:11)
at tryCatch (/home/user/git/saplearninghub-pdf-downloader/node_modules/regenerator-runtime/runtime.js:45:40)
at Generator.invoke [as _invoke] (/home/user/git/saplearninghub-pdf-downloader/node_modules/regenerator-runtime/runtime.js:274:22)
at Generator.prototype.<computed> [as next] (/home/user/git/saplearninghub-pdf-downloader/node_modules/regenerator-runtime/runtime.js:97:21)
at asyncGeneratorStep (/home/user/git/saplearninghub-pdf-downloader/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/home/user/git/saplearninghub-pdf-downloader/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by chunhui323** [comment]
Dear AZn5ReD,
I am new to github.
Could you let me know the complete command for "rs"?It sounds like it will allow me to retry.
Thanks,Lek

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 26, 2021 at 22:09, reallyallnamestaken<notifications@github.com> wrote:   


Confirmed. Getting exact same issue. Seem to be timing issue. If you access the site manually this will be the point where you observe some waiting for the redirect.
As a workaround I run in test mode and enter "rs" when it fails. Eventually it will go through. may take quite a few times though.

Output:

Redirected to: https://accounts.sap.com/saml2/idp/usso/Learning_Hub
Can't connect :(
Error: Error during init
at _callee3$ (/home/user/git/saplearninghub-pdf-downloader/src/main.js:30:11)
at tryCatch (/home/user/git/saplearninghub-pdf-downloader/node_modules/regenerator-runtime/runtime.js:45:40)
at Generator.invoke [as _invoke] (/home/user/git/saplearninghub-pdf-downloader/node_modules/regenerator-runtime/runtime.js:274:22)
at Generator.prototype. [as next] (/home/user/git/saplearninghub-pdf-downloader/node_modules/regenerator-runtime/runtime.js:97:21)
at asyncGeneratorStep (/home/user/git/saplearninghub-pdf-downloader/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/home/user/git/saplearninghub-pdf-downloader/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by reallyallnamestaken** [comment]
From the README.md:

----------------------------
## Test

Copy the [config.json](config.json) file into the root of the project with the name `config_test.json`. This file will be use by the test command. It also is gitignored so that no credentials will be committed.

```bash
npm run dev
```
----------------------------

Basically when it fail as before it will wait for instructions or changes to the files. This is when you type "rs" and hit Enter. It will start again.
If also change DEBUG to true in the config file, you can observe what is going on in the browser.

**Comment by chunhui323** [comment]
Thank You,
I reinstalled nodejs, clone the repository, followed the steps again.

And retry the following command till it able to connect
 npm run start.
