### ISSUE TITLE
My ID is my email, I don't have S-User

### ISSUE THREAD

**Issue by nieloga** [AZn5ReD/saplearninghub-pdf-downloader#26]
Hello Azn5ReD
I am trying to connect using my email address because the account was created with this email in success factor application.
Is necessary to  use the script with S-User? 
Because I'm facing:

Error while reading config file: SyntaxError: Unexpected token U in JSON at position 228
    at JSON.parse (<anonymous>)
    at Module.<anonymous> (C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:18:846279)
    at t (C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:1:110)
    at C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:1:902
    at Object.<anonymous> (C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:1:913)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
Starting script...
Going to: https://performancemanager.successfactors.eu/sf/learning?company=learninghub
Entering login: da***********@gmail.com
Entering password: ***
Submiting...
Redirected to: https://account.sap.com/core/login-as/autologin/da***********@gmail.com?apiKey=3_8nyT5U5bgmcYd76h25LbEmWhqOWeM39-36YxT90-TFTHoCC5AWQbqzABxbwJMaxU&reqId=https%253A%252F%252Fwww.successfactors.eu%252Flearninghub&samlContext=184876214373_f2d7468b-29a4-4cc0-86a4-99cdcd31edce
Can't connect :(
Error: Error during init
    at C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:18:853146
    at s (C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:1:1024111)
    at Generator._invoke (C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:1:1023864)
    at Generator.forEach.e.<computed> [as next] (C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:1:1024468)
    at t (C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:1:13893)
    at c (C:\Users\Personal\Downloads\Sap1\saplearninghub-pdf-downloader-1.1.0\dist\index.js:1:14104)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by AZn5ReD** [comment]
Hi,

Using an email shouldn't be a problem. Can you log in using your credentials to https://performancemanager.successfactors.eu/sf/learning?company=learninghub ?
