### ISSUE TITLE
waiting for selector "#progressIndicator" failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by rku2201** [AZn5ReD/saplearninghub-pdf-downloader#40]
for almost 8 month I was able to download from SAP learning hub. But now it is for me not possible I got the following error.
Entering login: SXXXXXXXXX
Entering password: ***
Submiting...
Redirected to: https://account.sap.com/core/login-as/autologin?reqId=https%253A%252F%252Fwww.successfactors.eu%252Flearninghub&samlContext=eu1_184876214373_b61e62bd-47f0-4b03-a6bf-bd8a432cf1fb
Connected :)
Initialize file
URL Template: https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/Assessment/HATD20_EN_Col17/xml/topic$$$.svg
File path: C:\tmp/HATD20_EN_Col17.pdf
a: waiting for selector "#progressIndicator" failed: timeout 30000ms exceeded
    at new u (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:1093139)
    at n.DOMWorld._waitForSelectorOrXPath (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:1091809)
    at n.DOMWorld.waitForSelector (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:1091208)
    at l.waitForSelector (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:848085)
    at l.<anonymous> (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:7115)
    at x.waitForSelector (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:85644)
    at c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:20:842165
    at u (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:1035204)
    at Generator._invoke (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:1034957)
    at Generator.next (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:1035567)
  -- ASYNC --
    at l.<anonymous> (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:7092)
    at x.waitForSelector (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:85644)
    at c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:20:842165
    at u (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:1035204)
    at Generator._invoke (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:1034957)
    at Generator.next (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:1035567)
    at t (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:13931)
    at c (c:\Users\Rudi\Downloads\saplearninghub-pdf-downloader-master\dist\index.js:1:14142)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Whenn using the --debug=true. Every thing seems to be ok, because, the browser started, the login ist correct and the HATD20_EN_Col17 will open. After a while I get the Info time execeeded. And nothing happens.
Any Idea
Kind Regards
RKu2201

**Comment by Stuff4All** [comment]
Same issue. It used to work: maybe it needs to be adjusted
