### ISSUE TITLE
Error running application on Linux

### ISSUE THREAD

**Issue by elpreto** [AZn5ReD/saplearninghub-pdf-downloader#7]
Hi.

I wasn't able to run it on windows, so I installed it on Linux.
This is the error I get while running it.

elpreto@elpreto-VirtualBox:~/Downloads/saplearninghub-pdf-downloader-1.0.0$ npm run start

> saplearninghub-pdf-downloader@1.0.0 start /home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0
> env NODE_ENV=production node ./dist/index.js

Starting script...
(node:11450) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Target dir ./target_dir doesn't exist
Directory ./target_dir created
Going to: https://learninghub.sap.com/login
Entering login: SXXXXXXXXXX
Entering password: ***
Error during login: Error: Execution context was destroyed, most likely because of a navigation.
    at P (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:60522)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async n.ExecutionContext._evaluateInternal (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:60028)
    at async o.evaluateHandle (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:20934)
    at async o.$ (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:27288)
    at async DOMWorld.$ (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1078234)
    at async DOMWorld.type (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1081796)
  -- ASYNC --
    at n.ExecutionContext.<anonymous> (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:7836)
    at o.evaluateHandle (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:20964)
    at o.<anonymous> (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:7859)
    at o.$ (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:27299)
    at o.<anonymous> (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:7859)
    at DOMWorld.$ (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1078242)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DOMWorld.type (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1081796)
  -- ASYNC --
    at f.<anonymous> (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:7836)
    at W.type (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:55707)
    at /home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:18:847473
    at s (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1024921)
    at Generator._invoke (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1024674)
    at Generator.forEach.e.<computed> [as next] (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1025278)
    at t (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:12899)
    at c (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:13110)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Error during init
    at /home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:18:854296
    at s (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1024921)
    at Generator._invoke (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1024674)
    at Generator.forEach.e.<computed> [as next] (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:1025278)
    at t (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:12899)
    at c (/home/elpreto/Downloads/saplearninghub-pdf-downloader-1.0.0/dist/index.js:1:13110)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by elpreto** [comment]
Is there a specific version of Node I shuold use or something like that?
I can't find the way to run it succesfully.

**Comment by AZn5ReD** [comment]
Well, I'm using the version 12.19.0.

It is weird because it looks like a navigation error (try googling the error message). But I'm using [waitForSelector](https://github.com/AZn5ReD/saplearninghub-pdf-downloader/blob/043f6e1c04a4a1a6521dee72887256eb52571fcb/src/navigation.js#L26), so puppeteer shoud be waiting for the password field...
Do you have a slow internet connection ?

**Comment by elpreto** [comment]
Hi.

Sorry, I checked the navigation.js you mentioned, and it was different than mine.
I was using the 1.0 release instead of the latest code.

It works now, thanks :D
