### ISSUE TITLE
Redirected to: chrome-error://chromewebdata/

### ISSUE THREAD

**Issue by sag8** [AZn5ReD/saplearninghub-pdf-downloader#8]
Something broke out of the blue. I have downloaded some books in the past few days and also downloaded some today. All worked well and all of a sudden, started getting "Redirected to: chrome-error://chromewebdata/" error, and nothing downloads now. Tried several books.

Complete error is given below. Username withheld. Although I'm sure I'm entering the correct credentials as I have tried two accounts.

````
> saplearninghub-pdf-downloader@1.0.0 start d:\GitHub\saplearninghub-pdf-downloader
> set NODE_ENV=production && node ./dist/index.js

Starting script...
(node:27004) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Going to: https://learninghub.sap.com/login
Entering login: ***
Entering password: ***
Submiting...
Redirected to: https://accounts.sap.com/saml2/idp/sso
Redirected to: https://learninghub.sap.com/saml2/sp/acs/a00026fd2/a00026fd2
Connected :)
No cookie consent
Navigating to SuccessFactor
Redirected to: https://learninghub.sap.com/?languagePrompt=true
Redirected to: chrome-error://chromewebdata/
Error while navToSF Navigation timeout of 30000 ms exceeded
    at d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:885181
    at async FrameManager.waitForFrameNavigation (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:879570)
    at async f.waitForNavigation (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:874408)
    at async W.waitForNavigation (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:50230)
  -- ASYNC --
    at f.<anonymous> (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:7836)
    at W.waitForNavigation (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:50267)
    at W.<anonymous> (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:7859)
    at d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:18:940292
    at s (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066296)
    at Generator._invoke (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066049)
    at Generator.forEach.e.<computed> [as next] (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066653)
    at t (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:12899)
    at c (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:13110)
    at d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:13169
  -- ASYNC --
    at W.<anonymous> (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:7836)
    at d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:18:940292
    at s (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066296)
    at Generator._invoke (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066049)
    at Generator.forEach.e.<computed> [as next] (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066653)
    at t (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:12899)
    at c (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:13110)
    at d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:13169
    at new Promise (<anonymous>)
    at d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:13050
Initialize file
URL Template: https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/TFIN52_1_EN_Col15_R1.3/xml/topic$$$.svg
File path: D:\Clouds\Mega\LearningHub Downloads/TFIN52_1_EN_Col15_R1.3.pdf
waiting for selector "#progressIndicator" failed: timeout 30000ms exceeded
    at new P (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1116938)
    at DOMWorld._waitForSelectorOrXPath (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1123706)
    at DOMWorld.waitForSelector (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1123294)
    at f.waitForSelector (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:876002)
    at f.<anonymous> (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:7859)
    at W.waitForSelector (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:57065)
    at d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:18:944780
    at s (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066296)
    at Generator._invoke (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066049)
    at Generator.forEach.e.<computed> [as next] (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066653)
  -- ASYNC --
    at f.<anonymous> (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:7836)
    at W.waitForSelector (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:57065)
    at d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:18:944780
    at s (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066296)
    at Generator._invoke (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066049)
    at Generator.forEach.e.<computed> [as next] (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:1066653)
    at t (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:12899)
    at c (d:\GitHub\saplearninghub-pdf-downloader\dist\index.js:1:13110)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
````
Could you have a look, please? 

Thanks.

**Comment by sag8** [comment]
Figured that navigation.js has to be played around with. I tried many things to fix it but nothing really changed. In the end, restored the original code. Built it again and reran. And it's working now. No idea what changed. 

Closing the issue.
